CREATE DATABASE EVACINA;

USE EVACINA;

CREATE TABLE VACINA(
	NOME_VAC VARCHAR(15) NOT NULL,
	RESGISTRO_VAC VARCHAR(4) NOT NULL,
	APLICACAO CHAR(2) NOT NULL,
	IFA VARCHAR(10) NOT NULL,
	QUANTIDADE_DOSES INT(1) NOT NULL,
	TEMPO_ENTRE_DOSES INT(4),
	VALIDADE_VAC INT(3) NOT NULL,
	DOSES_FRASCO INT(2) NOT NULL)

ALTER TABLE VACINA
	ADD CONSTRAINT VACPK
	PRIMARY KEY (REGISTRO_VAC),
	ADD CONSTRAINT VACSK
	UNIQUE (NOME_VAC);

CREATE TABLE COMORBIDADES_VAC(
	REGISTRO_VAC VARCHAR(4) NOT NULL,
	COMORBIDADE CHAR(25) NOT NULL)

ALTER TABLE COMORBIDADES_VAC
	ADD CONSTRAINT COMVACPK
	PRIMARY KEY (REGISTRO_VAC, COMORBIDADE),
	ADD CONSTRAINT COMVACFK
	FOREIGN KEY (REGISTRO_VAC) REFERENCES VACINA(REGISTRO_VAC)
	ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE LABORATORIO(
	NOME_LAB VARCHAR(15) NOT NULL,
	NACIONALIDADE CHAR(2) NOT NULL)

ALTER TABLE LABORATORIO
	ADD CONSTRAINT LABPK
	PRIMARY KEY (NOME_LAB);

CREATE TABLE PRODUZ(
	REGISTRO_VAC VARCHAR(4) NOT NULL,
	NOME_LAB VARCHAR(15) NOT NULL,
	DATA_DE_PRODUÇÃO DATE NOT NULL)

ALTER TABLE PRODUZ
	ADD CONSTRAINT PRDZPK
	PRIMARY KEY (REGISTRO_VAC, NOME_LAB),
	ADD CONSTRAINT PDRZFK1
	FOREIGN KEY (REGISTRO_VAC) REFERENCES VACINA(REGISTRO_VAC)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	ADD CONSTRAINT PDRZFK2
	FOREIGN KEY (NOME_LAB) REFERENCES LABORATÓRIO(NOME_LAB)
	ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE LOTE(
	CODIGO_LT INT(8) NOT NULL,
	REGISTRO_VAC VARCHAR(4) NOT NULL)

ALTER TABLE LOTE
	ADD CONSTRAINT LTPK
	PRIMARY KEY (CODIGO_LT),
	ADD CONSTRAIN LTFK
	FOREIGN KEY (REGISTRO_VAC) REFERENCES VACINA(REGISTRO_VAC)
	ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE FRASCO(
	CODIGO_LT INT(8) NOT NULL,
	DATA_VALIDADE_F DATE NOT NULL)

CREATE TABLE POSTO_DE_VACINACAO(
	CNES INT(7) NOT NULL,
	NOME_PV CHAR(15) NOT NULL,
	MUNICIO_PV CHAR(30) NOT NULL,
	QTD_DOSES_APLICADAS INT(5),
	DOSES_EM_ESTOQUE INT(5))

ALTER TABLE POSTO_DE_VACINACAO
	ADD CONSTRAINT PVPK
	PRIMARY KEY (CNES);


CREATE TABLE RECEBE(
	CODIGO_LT INT(8) NOT NULL,
	CNES INT(7) NOT NULL,
	QUANTIDADE_DOSES INT(4) NOT NULL)

ALTER TABLE RECEBE
	ADD CONSTRAINT RECPK
	PRIMARY KEY (CODIGO_LT, CNES),
	ADD CONSTRAINT RECFK1
	FOREIGN KEY (CODIGO_LT) REFERENCES LOTE(CODIGO_LT)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	ADD CONSTRAINT RECFK2
	FOREIGN KEY (CNES) REFERENCES POSTO_DE_VACINAÇÃO(CNES)
	ON DELETE RESTRICT ON UPDATE CASCADE;


CREATE TABLE CIDADAO(
	NOME_CD CHAR(15) NOT NULL,
	CPF INT(11),
	CNS INT(15) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	CEP INT(8),
	DATA_DE_NASCIMENTO DATE NOT NULL,
	IDADE INT(3) NOT NULL,
	MUNICIPIO_CD CHAR(30) NOT NULL)

ALTER TABLE CIDADAO
	ADD CONSTRAINT CDPK1
	PRIMARY KEY(CNS),
	ADD CONSTRAINT CDPK2
	UNIQUE(CPF);

CREATE TABLE COMORBIDADE_ALERGIA_CD(
	CNS INT(15) NOT NULL,
	COMORBIDADE_CD CHAR(30),
	ALERGIA CHAR(30))

ALTER TABLE COMORBIDADE_ALERGIA_CD
	ADD CONSTRAINT CACDPK
	PRIMARY KEY (CNS),
	ADD CONSTRAINT CACDFK
	FOREIGN KEY (CNS) REFERENCES CIDADAO(CNS)
	ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE FUNCIONARIO(
	CPF INT(11) NOT NULL,
	CARGO CHAR(20),
	CATEGORIA CHAR(20) NOT NULL)

ALTER TABLE FUNCIONARIO
	ADD CONSTRAINT FUNPK
	PRIMARY KEY CPF,
	ADD CONSTRAINT FUNFK
	FOREIGN KEY (CPF) REFERENCES CIDADAO(CPF)
	ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE TRABALHA(
	CNES INT(7) NOT NULL,
	CPF_FUN INT(11) NOT NULL)

ALTER TABLE TRABALHA
	ADD CONSTRAINT TRABPK
	PRIMARY KEY (CNES, CPF_FUN),
	ADD CONSTRAINT TRABFK1
	FOREIGN KEY (CNES) REFERENCES POSTO_DE_VACINACAO(CNES)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	ADD CONSTRAINT TRABFK2
	FOREIGN KEY (CPF_FUN) REFERENCES FUNCIONARIO(CPF_FUN)
	ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE APLICA(
	CNS_CD INT(15) NOT NULL,
	CPF_FUN INT(11) NOT NULL,
	CODIGO_LT INT(8) NOT NULL,
	DATA_APLICACAO DATE NOT NULL)

ALTER TABLE APLICA
	ADD CONSTRAINT APLPK
	PRIMARY KEY (CNS_CD, CODIGO_LT),
	ADD CONSTRAINT APLFK1
	FOREIGN KEY (CNS_CD) REFERENCES CIDADAO(CNS)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	ADD CONSTRAINT APLFK2
	FOREIGN KEY (CPF_FUN) REFERENCES FUNCINARIO(CPF)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	ADD CONSTRAINT APLFK3
	FOREIGN KEY (CODIGO_LT) REFERENCES LOTE(CODIGO_LT)
	ON DELETE RESTRICT ON UPDATE CASCADE;
